apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-demo
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: env/production
    repoURL: https://github.com/iliasnaamane/argocd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
